# Generated by Django 5.2.8 on 2025-12-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='media/articulo_defecto.png', null=True, upload_to='media'),
        ),
    ]
